# Generated by Django 3.1.3 on 2020-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=63)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
                ('is_published', models.BooleanField()),
                ('source', models.TextField()),
                ('options', models.JSONField()),
            ],
        ),
    ]
