# Generated by Django 3.1.3 on 2020-11-29 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_remove_slideshow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='options',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='slug',
            field=models.SlugField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='source',
            field=models.TextField(verbose_name='Source code'),
        ),
    ]
